server:
  port: 8081

spring:
  jpa:
    database: H2
    database-platform: org.hibernate.dialect.H2Dialect
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:quizlet;DB_CLOSE_ON_EXIT=TRUE';DB_CLOSE_DELAY=-1;
    username: sa
    password: sa
  flyway:
    locations: classpath:db/migration/h2
    enabled: true
  h2:
    console:
      enabled: true
      path: /h2

mybatis:
  mapper-locations: classapth*:**/mappers/*.xml
  configuration:
    map-underscore-to-camel-case: true